
import { Category } from "@/types/niche-scout";

export const categories: Category[] = [
  { label: "Education & Learning", value: "education" },
  { label: "Entertainment", value: "entertainment" },
  { label: "Technology & Gaming", value: "tech" },
  { label: "Lifestyle & Health", value: "lifestyle" },
  { label: "Business & Finance", value: "business" },
  { label: "Arts & Creativity", value: "arts" },
  { label: "Travel & Adventure", value: "travel" },
  { label: "Sports & Fitness", value: "sports" },
  { label: "Kids & Family", value: "kids" },
];

export const subcategoryMap: Record<string, Category[]> = {
  education: [
    { label: "Online Courses & Tutorials", value: "education.courses" },
    { label: "Language Learning", value: "education.language" },
    { label: "Science & Explainers", value: "education.science" },
    { label: "History & Culture", value: "education.history" },
    { label: "DIY Skills & How-To", value: "education.diy" },
    { label: "Career Development", value: "education.career" },
  ],
  entertainment: [
    { label: "Comedy & Sketches", value: "entertainment.comedy" },
    { label: "Reaction Videos", value: "entertainment.reaction" },
    { label: "Music & Music Videos", value: "entertainment.music" },
    { label: "Movie & TV Reviews", value: "entertainment.reviews" },
    { label: "Vlogging & Daily Life", value: "entertainment.vlogs" },
    { label: "Animation & Cartoons", value: "entertainment.animation" },
  ],
  tech: [
    { label: "Smartphones & Gadgets", value: "tech.gadgets" },
    { label: "PC & Console Gaming", value: "tech.gaming" },
    { label: "Programming & Development", value: "tech.programming" },
    { label: "AI & Machine Learning", value: "tech.ai" },
    { label: "Crypto & Blockchain", value: "tech.crypto" },
    { label: "Tech News & Reviews", value: "tech.news" },
  ],
  lifestyle: [
    { label: "Fashion & Style", value: "lifestyle.fashion" },
    { label: "Health & Wellness", value: "lifestyle.health" },
    { label: "Beauty & Skincare", value: "lifestyle.beauty" },
    { label: "Home Decor & Design", value: "lifestyle.home" },
    { label: "Food & Cooking", value: "lifestyle.food" },
    { label: "Personal Development", value: "lifestyle.development" },
  ],
  business: [
    { label: "Entrepreneurship", value: "business.entrepreneurship" },
    { label: "Stock Market & Investing", value: "business.investing" },
    { label: "Real Estate", value: "business.realestate" },
    { label: "Digital Marketing", value: "business.marketing" },
    { label: "Freelancing & Side Hustles", value: "business.freelancing" },
    { label: "Career Advice", value: "business.career" },
  ],
  arts: [
    { label: "Digital Art & Design", value: "arts.digital" },
    { label: "Music Production", value: "arts.music" },
    { label: "Photography & Videography", value: "arts.photography" },
    { label: "Drawing & Painting", value: "arts.drawing" },
    { label: "Crafts & DIY", value: "arts.crafts" },
    { label: "Writing & Storytelling", value: "arts.writing" },
  ],
  travel: [
    { label: "Travel Vlogging", value: "travel.vlogging" },
    { label: "Budget Travel & Hacks", value: "travel.budget" },
    { label: "Food Tourism", value: "travel.food" },
    { label: "Adventure & Outdoor", value: "travel.adventure" },
    { label: "Digital Nomad Lifestyle", value: "travel.nomad" },
    { label: "Solo Travel", value: "travel.solo" },
  ],
  sports: [
    { label: "Fitness & Workouts", value: "sports.fitness" },
    { label: "Sports Commentary", value: "sports.commentary" },
    { label: "Extreme Sports", value: "sports.extreme" },
    { label: "Outdoor Recreation", value: "sports.outdoor" },
    { label: "Combat Sports & Martial Arts", value: "sports.combat" },
    { label: "Sports Highlights & Analysis", value: "sports.analysis" },
  ],
  kids: [
    { label: "Nursery Rhymes & Songs", value: "kids.nursery" },
    { label: "Educational Cartoons", value: "kids.educational" },
    { label: "Toys & Unboxing", value: "kids.toys" },
    { label: "Crafts & Activities", value: "kids.crafts" },
    { label: "Bedtime Stories", value: "kids.stories" },
    { label: "Family Vlogs", value: "kids.family" },
    { label: "Animation for Kids", value: "kids.animation" },
    { label: "Kids Music Videos", value: "kids.music" },
    { label: "Baby Sensory Videos", value: "kids.sensory" },
    { label: "Learning Colors & Shapes", value: "kids.learning" },
    { label: "Kids Cooking & Food", value: "kids.cooking" },
    { label: "Alphabet & Counting Songs", value: "kids.alphabet" },
    { label: "Puppet Shows", value: "kids.puppets" },
    { label: "Sing-Alongs", value: "kids.singalong" },
  ],
};
