{{- if and .Values.metrics.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-metrics
  labels:
    app: {{ template "alfred.name" . }}
    chart: {{ template "alfred.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: db-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "alfred.name" . }}
      release: {{ .Release.Name }}
      component: db-metrics
  template:
    metadata:
      labels:
        app: {{ template "alfred.name" . }}
        release: {{ .Release.Name }}
        component: db-metrics
    spec:
      containers:
        - name: db-metrics
          image: "{{ .Values.dbMetrics.image.repository }}:{{ .Values.dbMetrics.image.tag }}"
          imagePullPolicy: {{ .Values.dbMetrics.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.dbMetrics.service.port }}
            - name: metrics
              containerPort: {{ .Values.dbMetrics.service.metricsPort }}
          env:
            - name: ALFRED_ENVIRONMENT
              value: {{ .Values.global.environment }}
            - name: DB_USER
              value: {{ .Values.dbMetrics.environment.DB_USER }}
            - name: DB_NAME
              value: {{ .Values.dbMetrics.environment.DB_NAME }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
          resources:
            {{- toYaml .Values.dbMetrics.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 45
            periodSeconds: 15
            timeoutSeconds: 20
{{- end }}
