# Staging-specific values for Alfred Helm chart

# Inherit base values
# Override staging-specific settings

# Enable Slack MCP Gateway for staging
slackMcpGateway:
  enabled: true
  image:
    repository: ghcr.io/locotoki/alfred-platform/slack_mcp_gateway
    tag: "0.1.0-rc3"
    digest: "sha256:3cf61e62e5e26849e4aa4ed3da53c8a5e03141739a0fd5a9cd2473aca772c057"
    pullPolicy: Always

  # Environment configuration
  envFromSecret: slack-mcp-gateway-secrets

  # Resource allocation for staging
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

  # Replica count for staging
  replicaCount: 1

  # Service configuration
  service:
    type: ClusterIP
    port: 80
    targetPort: 3000

  # Health check configuration
  livenessProbe:
    httpGet:
      path: /health
      port: 3000
    initialDelaySeconds: 10
    periodSeconds: 30

  readinessProbe:
    httpGet:
      path: /health
      port: 3000
    initialDelaySeconds: 5
    periodSeconds: 10

# Redis configuration for staging
redis:
  enabled: true
  auth:
    existingSecret: redis-password
    existingSecretPasswordKey: redis-password
