apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.crewaiA2aToken.name }}
  labels:
    {{- include "crewai.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secrets.crewaiA2aToken.key }}: {{ .Values.crewai.auth.token | b64enc | quote }}