version: "3.9"

x-common-env: &common
  CREWAI_ENDPOINT: "http://crewai:8080"
  CREWAI_API_KEY: "local-test"
  SLACK_WEBHOOK_URL: "http://mock-slack:80"
  N8N_BASIC_AUTH_USER: "admin"
  N8N_BASIC_AUTH_PASSWORD: "admin"

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:1.26.0
    ports: ["${N8N_PORT:-5678}:5678"]
    restart: unless-stopped
    environment: *common
    volumes:
      - ./orchestration/n8n:/home/node/.n8n   # pre-load workflow

  crewai:
    image: python:3.12-slim
    ports: ["${CREWAI_PORT:-8080}:8080"]
    command: >
      python - <<'PY'
      import json, os
      from http.server import BaseHTTPRequestHandler, HTTPServer
      class H(BaseHTTPRequestHandler):
        def do_POST(self):
          self.rfile.read(int(self.headers['content-length']))
          resp={"action":"restart","reason":"PoC stub – always restart","deployment":"api","namespace":"default"}
          self.send_response(200); self.send_header("Content-Type","application/json"); self.end_headers()
          self.wfile.write(json.dumps(resp).encode())
      HTTPServer(("",8080),H).serve_forever()
      PY

  mock-slack:
    image: containous/whoami:latest
    ports: ["${SLACK_PORT:-3010}:80"]