version: '3.8'

services:
  # Test container that reproduces the issue with db-metrics
  db-metrics-test:
    build:
      context: ./rca
    container_name: db-metrics-test
    ports:
      - "9199:9091"
    volumes:
      - ./rca:/app
    environment:
      - SERVICE_NAME=test-service
      - SERVICE_URL=http://mock-service:80
      - CHECK_TYPE=http
      - HEALTH_PATH=/health
      - PORT=9091
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9091/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - alfred-network

  # Test container with fixed version
  db-metrics-fixed:
    build:
      context: ./rca
    container_name: db-metrics-fixed
    ports:
      - "9200:9091"
    volumes:
      - ./rca:/app
    command: ["python", "fix_app.py"]
    environment:
      - SERVICE_NAME=test-service
      - SERVICE_URL=http://mock-service:80
      - CHECK_TYPE=http
      - HEALTH_PATH=/health
      - PORT=9091
      - DEBUG_MODE=true
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9091/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - alfred-network

  # Additional test container to check service dependency
  mock-service:
    image: nginx:alpine
    container_name: mock-service
    ports:
      - "8081:80"
    volumes:
      - ./mock-health:/usr/share/nginx/html
    networks:
      - alfred-network

networks:
  alfred-network:
    external: true