{{- if .Values.slackApp.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alfred.fullname" . }}-slack-app
  labels:
    {{- include "alfred.labels" . | nindent 4 }}
    app.kubernetes.io/component: slack-app
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "alfred.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: slack-app
  template:
    metadata:
      labels:
        {{- include "alfred.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: slack-app
    spec:
      containers:
        - name: slack-app
          image: "{{ .Values.slackApp.image.repository }}:{{ .Values.slackApp.image.tag }}"
          imagePullPolicy: {{ .Values.slackApp.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ include "alfred.fullname" . }}-slack-app-secrets
            - configMapRef:
                name: {{ include "alfred.fullname" . }}-slack-app-config
          env:
            - name: SOCKET_MODE
              value: "{{ .Values.slackApp.env.SOCKET_MODE }}"
            - name: LOG_LEVEL
              value: "{{ .Values.slackApp.env.LOG_LEVEL }}"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.slackApp.resources | nindent 12 }}
      {{- with .Values.slackApp.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.slackApp.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.slackApp.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
