{{- if .Values.slackMcpGateway.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alfred.fullname" . }}-slack-mcp-gateway-config
  labels:
    {{- include "alfred.labels" . | nindent 4 }}
    app.kubernetes.io/component: slack-mcp-gateway
data:
  MCP_REQUEST_STREAM: {{ .Values.slackMcpGateway.config.MCP_REQUEST_STREAM | default "mcp.requests" | quote }}
  MCP_RESPONSE_STREAM: {{ .Values.slackMcpGateway.config.MCP_RESPONSE_STREAM | default "mcp.responses" | quote }}
  SLACK_APP_ENV: {{ .Values.slackMcpGateway.config.SLACK_APP_ENV | default "staging" | quote }}
{{- end }}
