name: Prometheus Health Probe CI

on:
  push:
    branches: [ main, "chore/healthcheck-prometheus-probe" ]
    paths:
      - 'cmd/prometheus-probe/**'
      - 'internal/prometheus/**'
      - 'tests/prometheus/**'
      - '.github/workflows/prometheus-health-probe.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'cmd/prometheus-probe/**'
      - 'internal/prometheus/**'
      - 'tests/prometheus/**'
      - '.github/workflows/prometheus-health-probe.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./cmd/prometheus-probe

    - name: Test
      run: go test -v ./internal/prometheus

    - name: Integration Test
      run: |
        RUN_INTEGRATION_TESTS=1 go test -v ./tests/prometheus -tags=integration

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Install golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.56.2

    - name: Run golangci-lint
      run: golangci-lint run ./cmd/prometheus-probe/... ./internal/prometheus/...

  docker:
    runs-on: ubuntu-latest
    needs: [build, lint]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t alfred/healthcheck:prometheus-probe -f healthcheck/Dockerfile.prometheus .
        docker images
